# get id, type, label, comment, domain, range from ??

prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> 

select ?term ?domain ?range ?parentClass
where 
{ 
    ?term rdf:type ?type .
    OPTIONAL { 
        ?term rdfs:domain ?domain;
              rdfs:range ?range .
    }  
    OPTIONAL { ?term rdfs:subClassOf ?parentClass .}
}
