# get id, type, label, comment, domain, range from ??

prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> 

select ?term ?type ?label ?comment
where 
{ 
    ?term rdf:type ?type ;
        rdfs:label ?label .
    OPTIONAL { ?term rdfs:comment ?comment . } 
}
